import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Code2, Megaphone, Database } from "lucide-react";

const tabs = [
  {
    id: "engineering",
    icon: Code2,
    label: "Engineering",
  },
  {
    id: "marketing",
    icon: Megaphone,
    label: "Content & Marketing",
  },
  {
    id: "data",
    icon: Database,
    label: "Data Science",
  },
];

const tabContent = {
  engineering: {
    title: "Auto-generate documentation",
    description:
      "Let the AI analyze your codebase and generate comprehensive documentation, code comments, and API references automatically.",
    codePreview: `// Generated by NexusAI
/**
 * @function processUserData
 * @description Processes incoming user data
 * @param {Object} userData - The user data object
 * @returns {Promise<ProcessedUser>}
 */
export async function processUserData(userData: UserInput): Promise<ProcessedUser> {
  const validated = await validateSchema(userData);
  return transformToOutput(validated);
}`,
  },
  marketing: {
    title: "Generate compelling copy",
    description:
      "Create high-converting marketing copy, blog posts, and social media content that resonates with your target audience.",
    codePreview: `// Content Generation Pipeline
const campaign = await nexus.generate({
  type: "marketing_copy",
  tone: "professional",
  target: "B2B SaaS",
  channels: ["email", "linkedin", "landing_page"]
});

// Output: 50+ variations ready for A/B testing
console.log(campaign.variations.length);
// >>> 52`,
  },
  data: {
    title: "Intelligent data analysis",
    description:
      "Automatically analyze datasets, generate insights, and create predictive models without writing complex queries.",
    codePreview: `# Data Analysis with NexusAI
insights = nexus.analyze(
    dataset="sales_q4_2024.csv",
    objectives=["trends", "anomalies", "predictions"]
)

print(insights.summary)
# >>> "Revenue increased 23% QoQ. Detected 3 anomalies..."

insights.export_report("pdf")`,
  },
};

const Solutions = () => {
  const [activeTab, setActiveTab] = useState("engineering");
  const content = tabContent[activeTab as keyof typeof tabContent];

  return (
    <section id="solutions" className="py-24 bg-surface">
      <div className="max-w-7xl mx-auto px-6">
        {/* Section Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="text-center mb-16"
        >
          <h2 className="font-display text-4xl md:text-5xl font-bold mb-4">
            Built for every team
          </h2>
          <p className="text-muted-foreground text-lg max-w-xl mx-auto">
            Whether you are coding, writing, or analyzing, Nexus samples.
          </p>
        </motion.div>

        <div className="grid lg:grid-cols-[280px_1fr] gap-8">
          {/* Tabs */}
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="space-y-2"
          >
            {tabs.map((tab) => (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl text-left transition-all duration-200 ${
                  activeTab === tab.id
                    ? "bg-primary text-primary-foreground"
                    : "text-muted-foreground hover:bg-muted hover:text-foreground"
                }`}
              >
                <tab.icon className="w-5 h-5" />
                <span className="font-medium">{tab.label}</span>
              </button>
            ))}
          </motion.div>

          {/* Content */}
          <AnimatePresence mode="wait">
            <motion.div
              key={activeTab}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              transition={{ duration: 0.3 }}
              className="bg-card rounded-2xl border border-border overflow-hidden"
            >
              {/* Window Header */}
              <div className="flex items-center gap-2 px-4 py-3 bg-surface-elevated border-b border-border">
                <div className="flex gap-2">
                  <div className="w-3 h-3 rounded-full bg-red-500/80" />
                  <div className="w-3 h-3 rounded-full bg-yellow-500/80" />
                  <div className="w-3 h-3 rounded-full bg-green-500/80" />
                </div>
              </div>

              <div className="p-8">
                <h3 className="font-display text-2xl font-semibold mb-3">
                  {content.title}
                </h3>
                <p className="text-muted-foreground mb-8 max-w-xl">
                  {content.description}
                </p>

                {/* Code Preview */}
                <div className="bg-background rounded-xl p-6 border border-border overflow-x-auto">
                  <pre className="font-mono text-sm text-muted-foreground whitespace-pre-wrap">
                    {content.codePreview}
                  </pre>
                </div>

                <div className="mt-6 flex justify-end">
                  <button className="px-4 py-2 rounded-lg bg-primary text-primary-foreground text-sm font-medium hover:bg-primary/90 transition-colors">
                    Try it now
                  </button>
                </div>
              </div>
            </motion.div>
          </AnimatePresence>
        </div>
      </div>
    </section>
  );
};

export default Solutions;
